<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="widget widget-new-products">
        <?php if ($this->getData('params/title')): ?>
            <div class="widget-title">
                <h2><?php echo $this->__($this->getData('params/title')) ?></h2>
            </div>
        <?php endif; ?>
        <div class="widget-products">
            <?php echo $this->getPagerHtml() ?>
            <?php $_columnCount = $this->getData('params/columns_count'); ?>
            <?php $i = 0;
            foreach ($_products->getItems() as $_product): ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid">
                <?php endif ?>
                <div>
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
                       class="product-image"><img
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($this->getData('params/image_size')) ?>"
                                width="<?php echo $this->getData('params/image_size') ?>" height="<?php echo $this->getData('params/image_size') ?>"
                                alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/></a>
                    <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h3>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                <?php if ($i % $_columnCount == 0 || $i == count($_products)): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
